openapi: 3.0.0
info:
  title: User Service API
  description: API cho quản lý người dùng và xác thực
  version: 1.0.0

servers:
  - url: http://localhost:8081/api
    description: Local development server

paths:
  /users/register:
    post:
      summary: Đăng ký tài khoản mới
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Tạo tài khoản thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Dữ liệu không hợp lệ
        '409':
          description: Username hoặc email đã tồn tại

  /users/login:
    post:
      summary: Đăng nhập
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Thông tin đăng nhập không chính xác

  /users/profile:
    get:
      summary: Lấy thông tin người dùng
      tags:
        - User Management
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Chưa xác thực
        '404':
          description: Không tìm thấy người dùng

    put:
      summary: Cập nhật thông tin người dùng
      tags:
        - User Management
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Dữ liệu không hợp lệ
        '401':
          description: Chưa xác thực

components:
  schemas:
    UserRegistration:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
        fullName:
          type: string
        phoneNumber:
          type: string

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/UserResponse'

    UserResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        fullName:
          type: string
        role:
          type: string
        createdAt:
          type: string
          format: date-time

    UserProfile:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        fullName:
          type: string
        phoneNumber:
          type: string
        role:
          type: string
        createdAt:
          type: string
          format: date-time

    UpdateProfileRequest:
      type: object
      properties:
        fullName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
          format: email

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 