#spring:
#  application:
#    name: notification-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/movie_ticketing?useSSL=false&serverTimezone=UTC
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: dhm.hminh
#    password: wyvfwlcqcdfgxybs
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#server:
#  port: 8084
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#
#logging:
#  level:
#    com.example.notification: DEBUG
#    org.springframework.web: INFO
#    org.hibernate: INFO
#
## Enable async processing
#  task:
#    execution:
#      pool:
#        core-size: 4
#        max-size: 8
#        queue-capacity: 100