version: '3.8'

services:
  # Eureka Server
  eureka-server:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: eureka-server
    volumes:
      - ./eureka-server:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8762:8761"
    networks:
      - ticket-network

  # API Gateway
  api-gateway:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: api-gateway
    volumes:
      - ./api-gateway:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - movie-service
      - showtime-service
      - seat
      - booking-service
      - payment-service
      - notification-service
      - user-service
    networks:
      - ticket-network

  # Movie Service
  movie-service:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: movie-service
    volumes:
      - ./movie-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/movie_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
      - eureka-server
    networks:
      - ticket-network

  # Showtime Service
  showtime-service:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: showtime-service
    volumes:
      - ./showtime-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/showtime_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
      - eureka-server
    networks:
      - ticket-network

  # Seat Service
  seat:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: seat
    volumes:
      - ./seat:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/seat_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
      - eureka-server
    networks:
      - ticket-network

  # Booking Service
  booking-service:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: booking-service
    volumes:
      - ./booking-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/booking_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
      - seat
      - eureka-server
    networks:
      - ticket-network

  # Payment Service
  payment-service:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: payment-service
    volumes:
      - ./payment-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - eureka-server
    networks:
      - ticket-network

  # Notification Service
  notification-service:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: notification-service
    volumes:
      - ./notification-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      - eureka-server
    networks:
      - ticket-network

  # User Service
  user-service:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: user-service
    volumes:
      - ./user-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
      - eureka-server
    networks:
      - ticket-network

  # Stripe CLI
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to payment-service:9090/api/payments/webhook
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    networks:
      - ticket-network
    depends_on:
      - payment-service

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql:ro
    networks:
      - ticket-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9091:9090"
    networks:
      - ticket-network
    depends_on:
      - api-gateway
      - movie-service
      - showtime-service
      - seat
      - booking-service
      - payment-service
      - notification-service
      - user-service

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - ticket-network
    depends_on:
      - prometheus

volumes:
  mysql-data:

networks:
  ticket-network:
    driver: bridge