global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'movie-service:8080'
          - 'showtime-service:8080'
          - 'seat:8080'
          - 'booking-service:8080'
          - 'payment-service:8080'
          - 'notification-service:8080'
          - 'user-service:8080'